apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: matheuspatricio0/projeto-fiap:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://projetofiap.c0qwoqfpu6hy.us-east-1.rds.amazonaws.com:5432/projetofiap?currentSchema=public
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: mypassword
