apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: keycloak-hpa
  namespace: default-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keycloak-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80