name: Deploy Kubernetes Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar o Kubectl
      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Configurar o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Validar a configuração do Terraform
      - name: Terraform Validate
        run: terraform validate

      # Configurar as credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAUAVACLUHQKTELI3C
          aws-secret-access-key: scioI7T7Ck6Tvgr3clP8RZahViH1uUsddkS6TIn4
          aws-region: us-east-1

      # Atualizar o Kube Config para acessar o EKS
      - name: Update Kube Config
        run: aws eks update-kubeconfig --name nginx --region us-east-1

      # Deploy dos recursos no Kubernetes
      - name: Deploy Kubernetes Resources
        run: |
          kubectl apply -f k8s/app-deployment.yaml
          kubectl apply -f k8s/db-deployment.yaml
          kubectl apply -f k8s/db-pvc.yaml
          kubectl apply -f k8s/db-service.yaml
          kubectl apply -f k8s/hpa.yaml
          kubectl apply -f k8s/service.yaml
